### ISSUE TITLE
wq maketemplates causes OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by pshassett** [wq/wq.start#7]
I'm trying to follow the [instructions for creating a project](https://wq.io/1.2/docs/setup-local) on Windows 10, Python 3.8.5 AMD64.  Because of admin restrictions I'm unable to use WSL, so I am "manually" walking through the steps of the bash scripts referenced in the docs and translating to cmd-equivalent commands (this could potentially be a separate issue/pr for adding .bat equivalent scripts for the deploy.sh, runserver.sh, update_json.sh etc. scripts).

The first command in deploy.sh is `wq maketemplates` which I am calling identically to how it is used in deploy.sh but is raising the following error:

```(venv) (base) C:\Users\PHassett\Documents\opCert>wq maketemplates --django-dir db --input-dir master_templates --template-dir templates
c:\users\phassett\documents\venv\lib\site-packages\scss\selector.py:26: FutureWarning: Possible nested set at position 329
  SELECTOR_TOKENIZER = re.compile(r'''
Traceback (most recent call last):
  File "C:\Users\PHassett\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\PHassett\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PHassett\Documents\venv\Scripts\wq.exe\__main__.py", line 7, in <module>
  File "c:\users\phassett\documents\venv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\phassett\documents\venv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\phassett\documents\venv\lib\site-packages\wq\core\decorators.py", line 19, in invoke
    return super(ConfigGroup, self).invoke(ctx)
  File "c:\users\phassett\documents\venv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\phassett\documents\venv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\phassett\documents\venv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\phassett\documents\venv\lib\site-packages\wq\start\forms.py", line 217, in maketemplates
    result = subprocess.check_output(
  File "C:\Users\PHassett\Anaconda3\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\PHassett\Anaconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\PHassett\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\PHassett\Anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

I see that maketemplates may be deprecated? In which case the docs should be updated to reflect this.

Just getting started with this platform I am very impressed with its flexibility and capabilities.  I hope I can get a basic implementation up and running.  Any support is greatly appreciated.  Thanks!

**Comment by sheppard** [comment]
I overhauled [the documentation](https://wq.io/), including how to install the [new beta version](https://github.com/wq/wq/releases/v1.3.0b1) which does not require maketemplates at all.

**Comment by pshassett** [comment]
Awesome, thanks for the update!
